version: '2.4'

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: jauderho/dnscrypt-proxy:latest
    ports:
      - 5353:5353/udp
    restart: always
    volumes:
      - "./config:/config:rw"
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 51m
    mem_reservation: 16m
    cpus: 0.1
networks:
  default:
    external:
      name: pihole_default