version: "2.4"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: edgd1er/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.1.26:53:53/tcp" #192.168.1.26 = host ip
      - "192.168.1.26:53:53/udp"
      - "192.168.1.26:67:67/udp"
      - "192.168.1.26:80:80/tcp"
    environment:
      TZ: 'Asia/Jakarta'
      WEBPASSWORD: 'insertpasswordhere'
      ServerIP: '192.168.1.26' # host ip
    # Volumes store your data between container upgrades
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    mem_limit: 84m
    mem_reservation: 48m
    cpus: 0.5
