version: "2.4"

services:
  adguardhome:
    container_name: adguardhome
    image: hezhijie0327/adguardhome:latest
    ports:
      - "192.168.1.26:53:53/tcp"
      - "192.168.1.26:53:53/udp"
      - "192.168.1.26:67:67/udp"
      - "192.168.1.26:68:68/tcp"
      - "192.168.1.26:68:68/udp"
      - "192.168.1.26:80:80/tcp"
      - "192.168.1.26:443:443/tcp"
      - "192.168.1.26:853:853/tcp"
      - "192.168.1.26:3000:3000/tcp"
    environment:
      TZ: 'Asia/Jakarta'
    volumes:
      - './cert:/opt/adguardhome/cert/'
      - './conf:/opt/adguardhome/conf/'
      - './work:/opt/adguardhome/work/'
    restart: unless-stopped
    mem_limit: 96m
    mem_reservation: 64m
    cpus: 0.5
