version: "3.7"

services:
  vite:
    image: node:16-alpine
    container_name: vite-app
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - "192.168.1.26:3333:3333"
    command: npm run dev
    init: true
